/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NaoEntreguesRouteImport } from './routes/nao-entregues'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FluxoCaixaRouteImport } from './routes/fluxo-caixa'
import { Route as DreRouteImport } from './routes/dre'
import { Route as CentrosCustoRouteImport } from './routes/centros-custo'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as IndexRouteImport } from './routes/index'

const NaoEntreguesRoute = NaoEntreguesRouteImport.update({
  id: '/nao-entregues',
  path: '/nao-entregues',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoCaixaRoute = FluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const DreRoute = DreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const CentrosCustoRoute = CentrosCustoRouteImport.update({
  id: '/centros-custo',
  path: '/centros-custo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/centros-custo': typeof CentrosCustoRoute
  '/dre': typeof DreRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/nao-entregues': typeof NaoEntreguesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/centros-custo': typeof CentrosCustoRoute
  '/dre': typeof DreRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/nao-entregues': typeof NaoEntreguesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/centros-custo': typeof CentrosCustoRoute
  '/dre': typeof DreRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/nao-entregues': typeof NaoEntreguesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carteira'
    | '/centros-custo'
    | '/dre'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/nao-entregues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carteira'
    | '/centros-custo'
    | '/dre'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/nao-entregues'
  id:
    | '__root__'
    | '/'
    | '/carteira'
    | '/centros-custo'
    | '/dre'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/nao-entregues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraRoute: typeof CarteiraRoute
  CentrosCustoRoute: typeof CentrosCustoRoute
  DreRoute: typeof DreRoute
  FluxoCaixaRoute: typeof FluxoCaixaRoute
  FornecedoresRoute: typeof FornecedoresRoute
  NaoEntreguesRoute: typeof NaoEntreguesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nao-entregues': {
      id: '/nao-entregues'
      path: '/nao-entregues'
      fullPath: '/nao-entregues'
      preLoaderRoute: typeof NaoEntreguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-caixa': {
      id: '/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof FluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dre': {
      id: '/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof DreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centros-custo': {
      id: '/centros-custo'
      path: '/centros-custo'
      fullPath: '/centros-custo'
      preLoaderRoute: typeof CentrosCustoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraRoute: CarteiraRoute,
  CentrosCustoRoute: CentrosCustoRoute,
  DreRoute: DreRoute,
  FluxoCaixaRoute: FluxoCaixaRoute,
  FornecedoresRoute: FornecedoresRoute,
  NaoEntreguesRoute: NaoEntreguesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
